<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "item_food_beverage".
 *
 * @property integer $id
 * @property string $name
 * @property double $buy_price
 * @property double $sale_price
 * @property integer $quantity
 * @property integer $service_food_beverage_id
 * @property integer $sale_food_beverage_id
 *
 * @property \app\models\SaleFoodBeverage $saleFoodBeverage
 * @property \app\models\ServiceFoodBeverage $serviceFoodBeverage
 * @property string $aliasModel
 */
abstract class ItemFoodBeverage extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_food_beverage';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'buy_price', 'sale_price', 'quantity', 'service_food_beverage_id', 'sale_food_beverage_id'], 'required'],
            [['buy_price', 'sale_price'], 'number'],
            [['quantity', 'service_food_beverage_id', 'sale_food_beverage_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['sale_food_beverage_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SaleFoodBeverage::className(), 'targetAttribute' => ['sale_food_beverage_id' => 'id']],
            [['service_food_beverage_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ServiceFoodBeverage::className(), 'targetAttribute' => ['service_food_beverage_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'buy_price' => Yii::t('app', 'Buy Price'),
            'sale_price' => Yii::t('app', 'Sale Price'),
            'quantity' => Yii::t('app', 'Quantity'),
            'service_food_beverage_id' => Yii::t('app', 'Service Food Beverage ID'),
            'sale_food_beverage_id' => Yii::t('app', 'Sale Food Beverage ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSaleFoodBeverage()
    {
        return $this->hasOne(\app\models\SaleFoodBeverage::className(), ['id' => 'sale_food_beverage_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServiceFoodBeverage()
    {
        return $this->hasOne(\app\models\ServiceFoodBeverage::className(), ['id' => 'service_food_beverage_id']);
    }




}
