<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "order_food_beverage".
 *
 * @property integer $id
 * @property string $code_order
 * @property string $name
 * @property double $buy_price
 * @property double $sale_price
 * @property integer $quantity
 * @property string $status
 * @property string $order_date
 * @property integer $service_food_beverage_id
 * @property integer $user_id
 *
 * @property \app\models\ServiceFoodBeverage $serviceFoodBeverage
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class OrderFoodBeverage extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_PEDDING = 'Pedding';
    const STATUS_DONE = 'Done';
    const STATUS_PAID = 'Paid';
    const STATUS_CANCEL = 'Cancel';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_food_beverage';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code_order', 'name', 'buy_price', 'sale_price', 'quantity', 'order_date', 'service_food_beverage_id', 'user_id'], 'required'],
            [['buy_price', 'sale_price'], 'number'],
            [['quantity', 'service_food_beverage_id', 'user_id'], 'integer'],
            [['status'], 'string'],
            [['order_date'], 'safe'],
            [['code_order'], 'string', 'max' => 45],
            [['name'], 'string', 'max' => 255],
            [['service_food_beverage_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ServiceFoodBeverage::className(), 'targetAttribute' => ['service_food_beverage_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_PEDDING,
                    self::STATUS_DONE,
                    self::STATUS_PAID,
                    self::STATUS_CANCEL,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'code_order' => Yii::t('app', 'Code Order'),
            'name' => Yii::t('app', 'Name'),
            'buy_price' => Yii::t('app', 'Buy Price'),
            'sale_price' => Yii::t('app', 'Sale Price'),
            'quantity' => Yii::t('app', 'Quantity'),
            'status' => Yii::t('app', 'Status'),
            'order_date' => Yii::t('app', 'Order Date'),
            'service_food_beverage_id' => Yii::t('app', 'Service Food Beverage ID'),
            'user_id' => Yii::t('app', 'User ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServiceFoodBeverage()
    {
        return $this->hasOne(\app\models\ServiceFoodBeverage::className(), ['id' => 'service_food_beverage_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_PEDDING => Yii::t('app', 'Pedding'),
            self::STATUS_DONE => Yii::t('app', 'Done'),
            self::STATUS_PAID => Yii::t('app', 'Paid'),
            self::STATUS_CANCEL => Yii::t('app', 'Cancel'),
        ];
    }

}
