<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "order_ticket_has_car".
 *
 * @property integer $order_ticket_id
 * @property integer $order_electric_car_id
 *
 * @property \app\models\OrderTicket $orderTicket
 * @property \app\models\OrderElectricCar $orderElectricCar
 * @property string $aliasModel
 */
abstract class OrderTicketHasCar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_ticket_has_car';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_ticket_id', 'order_electric_car_id'], 'required'],
            [['order_ticket_id', 'order_electric_car_id'], 'integer'],
            [['order_ticket_id'], 'unique'],
            [['order_ticket_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\OrderTicket::className(), 'targetAttribute' => ['order_ticket_id' => 'id']],
            [['order_electric_car_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\OrderElectricCar::className(), 'targetAttribute' => ['order_electric_car_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'order_ticket_id' => Yii::t('app', 'Order Ticket ID'),
            'order_electric_car_id' => Yii::t('app', 'Order Electric Car ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderTicket()
    {
        return $this->hasOne(\app\models\OrderTicket::className(), ['id' => 'order_ticket_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderElectricCar()
    {
        return $this->hasOne(\app\models\OrderElectricCar::className(), ['id' => 'order_electric_car_id']);
    }




}
