<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "product_order".
 *
 * @property integer $id
 * @property string $order_code
 * @property string $details
 * @property string $order_date
 * @property string $done_date
 * @property string $status
 * @property integer $user_id
 *
 * @property \app\models\ItemOrder[] $itemOrders
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class ProductOrder extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_DRAFT = 'Draft';
    const STATUS_ORDER = 'Order';
    const STATUS_DONE = 'Done';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_order';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_code', 'details', 'order_date', 'user_id'], 'required'],
            [['details', 'status'], 'string'],
            [['order_date', 'done_date'], 'safe'],
            [['user_id'], 'integer'],
            [['order_code'], 'string', 'max' => 45],
            [['status'], 'unique'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_DRAFT,
                    self::STATUS_ORDER,
                    self::STATUS_DONE,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'order_code' => Yii::t('app', 'Order Code'),
            'details' => Yii::t('app', 'Details'),
            'order_date' => Yii::t('app', 'Order Date'),
            'done_date' => Yii::t('app', 'Done Date'),
            'status' => Yii::t('app', 'Status'),
            'user_id' => Yii::t('app', 'User ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemOrders()
    {
        return $this->hasMany(\app\models\ItemOrder::className(), ['product_order_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_DRAFT => Yii::t('app', 'Draft'),
            self::STATUS_ORDER => Yii::t('app', 'Order'),
            self::STATUS_DONE => Yii::t('app', 'Done'),
        ];
    }

}
