<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "report_in_ticket".
 *
 * @property double $total_price
 * @property string $date
 * @property string $aliasModel
 */
abstract class ReportInTicket extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'report_in_ticket';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['total_price'], 'number'],
            [['date'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'total_price' => Yii::t('app', 'Total Price'),
            'date' => Yii::t('app', 'Date'),
        ];
    }




}
