<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sale_food_beverage".
 *
 * @property integer $id
 * @property string $code_sale
 * @property string $status
 * @property string $date
 * @property integer $user_id
 *
 * @property \app\models\ItemFoodBeverage[] $itemFoodBeverages
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class SaleFoodBeverage extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_PEDDING = 'Pedding';
    const STATUS_DONE = 'Done';
    const STATUS_PAID = 'Paid';
    const STATUS_CANCEL = 'Cancel';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sale_food_beverage';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code_sale', 'date', 'user_id'], 'required'],
            [['status'], 'string'],
            [['date'], 'safe'],
            [['user_id'], 'integer'],
            [['code_sale'], 'string', 'max' => 45],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_PEDDING,
                    self::STATUS_DONE,
                    self::STATUS_PAID,
                    self::STATUS_CANCEL,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'code_sale' => Yii::t('app', 'Code Sale'),
            'status' => Yii::t('app', 'Status'),
            'date' => Yii::t('app', 'Date'),
            'user_id' => Yii::t('app', 'User ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemFoodBeverages()
    {
        return $this->hasMany(\app\models\ItemFoodBeverage::className(), ['sale_food_beverage_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_PEDDING => Yii::t('app', 'Pedding'),
            self::STATUS_DONE => Yii::t('app', 'Done'),
            self::STATUS_PAID => Yii::t('app', 'Paid'),
            self::STATUS_CANCEL => Yii::t('app', 'Cancel'),
        ];
    }

}
