<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "service_food_beverage".
 *
 * @property integer $id
 * @property string $name
 * @property double $buy_price
 * @property double $sale_price
 * @property string $photo
 * @property integer $status
 * @property string $date
 * @property integer $user_id
 * @property string $type
 *
 * @property \app\models\OrderFoodBeverage[] $orderFoodBeverages
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class ServiceFoodBeverage extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const TYPE_FOOD = 'Food';
    const TYPE_BEVERAGE = 'Beverage';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_food_beverage';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'buy_price', 'sale_price', 'date', 'user_id', 'type'], 'required'],
            [['buy_price', 'sale_price'], 'number'],
            [['status', 'user_id'], 'integer'],
            [['date'], 'safe'],
            [['type'], 'string'],
            [['name', 'photo'], 'string', 'max' => 45],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']],
            ['type', 'in', 'range' => [
                    self::TYPE_FOOD,
                    self::TYPE_BEVERAGE,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'buy_price' => Yii::t('app', 'Buy Price'),
            'sale_price' => Yii::t('app', 'Sale Price'),
            'photo' => Yii::t('app', 'Photo'),
            'status' => Yii::t('app', 'Status'),
            'date' => Yii::t('app', 'Date'),
            'user_id' => Yii::t('app', 'User ID'),
            'type' => Yii::t('app', 'Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderFoodBeverages()
    {
        return $this->hasMany(\app\models\OrderFoodBeverage::className(), ['service_food_beverage_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




    /**
     * get column type enum value label
     * @param string $value
     * @return string
     */
    public static function getTypeValueLabel($value){
        $labels = self::optsType();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column type ENUM value labels
     * @return array
     */
    public static function optsType()
    {
        return [
            self::TYPE_FOOD => Yii::t('app', 'Food'),
            self::TYPE_BEVERAGE => Yii::t('app', 'Beverage'),
        ];
    }

}
