<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "service_electric_car".
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property double $price
 * @property integer $status
 * @property string $date
 * @property integer $user_id
 *
 * @property \app\models\OrderElectricCar[] $orderElectricCars
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class ServiceElectricCar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_electric_car';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'name', 'price', 'date', 'user_id'], 'required'],
            [['price'], 'number'],
            [['status', 'user_id'], 'integer'],
            [['date'], 'safe'],
            [['code', 'name'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'code' => Yii::t('app', 'Code'),
            'name' => Yii::t('app', 'Name'),
            'price' => Yii::t('app', 'Price'),
            'status' => Yii::t('app', 'Status'),
            'date' => Yii::t('app', 'Date'),
            'user_id' => Yii::t('app', 'User ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderElectricCars()
    {
        return $this->hasMany(\app\models\OrderElectricCar::className(), ['service_electric_car_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




}
