<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "service_ticket".
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property double $price
 * @property string $date
 * @property string $remark
 * @property integer $user_id
 * @property integer $status
 * @property string $aliasModel
 */
abstract class ServiceTicket extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_ticket';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'price', 'date', 'remark', 'user_id'], 'required'],
            [['price'], 'number'],
            [['date'], 'safe'],
            [['remark'], 'string'],
            [['user_id', 'status'], 'integer'],
            [['code'], 'string', 'max' => 255],
            [['name'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Code',
            'name' => 'Name',
            'price' => 'Price',
            'date' => 'Date',
            'remark' => 'Remark',
            'user_id' => 'User ID',
            'status' => 'Status',
        ];
    }




}
