<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Are you want to delete this item.?' => '​ທ່ານ​​ຕ້ອງ​ການ​ລຶບ​ລາຍ​ການນີ້ບໍ່.?',
    'Create User' => 'ເພີ່ມ​ຜູ້​ໃຊ້',
    'Delete' => 'ລຶບ',
    'Off' => '​ເປິດ',
    'On' => '​ເປິດ',
    'Save' => '​ບັນ​ທືກ',
    'The requested page does not exist.' => '',
    'Update' => '​ແກ້​ໄຂ',
    'Update User: {name}' => '',
    'Users' => '​ຜູ້​ໃຊ້',
    'You are not allowed to {0} record #{1}' => '',
];